name: CI Build, Test, and Publish

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Grants permission to create releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest guymucs/tests

    - name: Build executable with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name GuyMucs guymucs/main.py
      shell: bash

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: GuyMucs-${{ matrix.os }}
        path: dist/GuyMucs*
        if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: GuyMucs-windows-latest
        path: release-packages/windows

    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: GuyMucs-macos-latest
        path: release-packages/macos

    - name: Upload release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release-packages/**/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        body: "Automatic build for GuyMucs on macOS and Windows"
        draft: false
        prerelease: false

