name: CI Build, Test, and Publish

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Grants permission to create releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest guymucs/tests

    - name: Build executable with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name GuyMucs guymucs/main.py
      shell: bash

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: GuyMucs-${{ matrix.os }}
        path: dist/GuyMucs*
        if-no-files-found: error

  build_deb:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Debian packaging environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Build Debian package
      run: |
        debuild -us -uc -b
      env:
        DEB_BUILD_OPTIONS: "parallel=$(nproc)"

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: GuyMucs-debian
        path: ../*.deb

  build_rpm:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up RPM packaging environment
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm

    - name: Build RPM package
      run: |
        fpm -s dir -t rpm -n GuyMucs -v 1.0 --prefix /usr/local/bin dist/GuyMucs

    - name: Upload RPM package
      uses: actions/upload-artifact@v3
      with:
        name: GuyMucs-rpm
        path: *.rpm

  publish:
    needs: [build, build_deb, build_rpm]
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: GuyMucs-windows-latest
        path: release-packages/windows

    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: GuyMucs-macos-latest
        path: release-packages/macos

    - name: Download Debian package
      uses: actions/download-artifact@v3
      with:
        name: GuyMucs-debian
        path: release-packages/debian

    - name: Download RPM package
      uses: actions/download-artifact@v3
      with:
        name: GuyMucs-rpm
        path: release-packages/rpm

    - name: Upload release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release-packages/**/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        body: "Automatic build for GuyMucs on macOS, Windows, Debian, and Fedora"
        draft: false
        prerelease: false

