name: CI Build, Test, and Publish

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Only macOS and Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest guymucs/tests

    - name: Build executable with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name GuyMucs guymucs/main.py
      shell: bash

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: GuyMucs-${{ matrix.os }}  # Name each artifact by OS
        path: dist/GuyMucs*

  publish:
    needs: build  # Ensures publish runs after build and test
    runs-on: ubuntu-latest
    steps:
    - name: Download built executables
      uses: actions/download-artifact@v3
      with:
        # Use a wildcard to download all available OS-specific artifacts
        name: [GuyMucs-windows-latest, GuyMucs-macos-latest]
        path: release-packages

    - name: Upload release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release-packages/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        body: "Automatic build for GuyMucs on macOS and Windows"
        draft: false
        prerelease: false

