name: CI Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest guymucs/tests

    - name: Build executable with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name GuyMucs guymucs/main.py
      shell: bash

    - name: Archive executable
      uses: actions/upload-artifact@v2
      with:
        name: GuyMucs-${{ matrix.os }}
        path: dist/GuyMucs*

